### ISSUE TITLE
Errores de conexión a la BD

### ISSUE THREAD

**Issue by yercito** [alvarodh5/harvey_unchained#1]
Hemos localizado un par de sitios donde parece que no funciona la conexión a la base de datos porque se está intentando acceder a una variable de entorno sin leerla del diccionario "os.environ".

https://github.com/alvarodh5/harvey_unchained/blob/e08faacd3917001676b9f1515cf81e291c35df4f/lib/instagram.py#L124

https://github.com/alvarodh5/harvey_unchained/blob/0ebec2e5af58fb63f392d7b45c4df11966999f22/lib/twitter/main.py#L34

**Comment by alvarodh5** [comment]
Efectivamente, tienes razón, teníamos las variables de entorno hardcodeadas y se nos ha olvidado actualizar eso 😢.

Gracias!
