### ISSUE TITLE
Cifrado débil de contraseñas

### ISSUE THREAD

**Issue by alsanchez** [alvarodh5/harvey_unchained#2]
Buenas. Soy Alex del equipo Ontic.

Ojeando el código del dashboard hemos visto que las contraseñas de usuario se almacenan hasheadas tanto en SHA1 como en MD5:

https://github.com/alvarodh5/harvey_unchained/blob/master/dashboard/login.php#L11

Este último algoritmo en particular es bastante débil y posiblemente no presentaría muchos obstáculos a la hora de intentar recuperar las contraseñas originales.

Si la aplicación requiere PHP 5.5 o superior una posible mejora sería utilizar la función nativa password_hash (que implementa el algoritmo bcrypt con salt):

http://php.net/manual/es/function.password-hash.php

Para versiones anteriores también existe la librería https://github.com/hautelook/phpass, que implementa el mismo algoritmo.

**Comment by juanvelascogomez** [comment]
Lo revisaremos @alsanchez, muchas gracias por la aportación!

**Comment by juanvelascogomez** [comment]
Tras deliberarlo con el equipo, en futuras actualizaciones de la herramienta modificaremos el cifrado empleado.

Gracias,

FWHIBBIT
