### ISSUE TITLE
Implementación aplicación de escritorio

### ISSUE THREAD

**Issue by Sawyer13** [alvarodh5/harvey_unchained#3]
¡Hola!

Hemos visto que estais realizando la aplicación a través de tecnologías web. ¿Habéis pensado implementar frameworks como electron? Esto os permitiria usar vuestro propio código e implementarlo en una aplicación de escritorio. Al usuario le resultaría super cómodo y podríais tenerlo tanto en Windows, como OSX como GNU/Linux. 

Aquí tenéis más información sobre electron: https://electronjs.org/

Hay una "demo" de prueba por si queréis testear: https://github.com/electron/electron-quick-start

¡Un saludo!

**Comment by juanvelascogomez** [comment]
Hola @Sawyer13 ! 

Tras valorar todo el equipo la posibilidad de usar electron hemos decidido continuar con nuestro framework. Sin embargo creemos que sería interesante de cara a conseguir que la herramienta sea multiplataforma. No obstante, consideramos que esto no es necesario, ya que al funcionar via web, se puede utilizar en cualquier dispositivo siempre y cuando el proyecto esté desplegado en un servidor compatible.

Muchas gracias por la sugerencia,

FWHIBBIT
