### ISSUE TITLE
Return 0 - WebScrapping Code

### ISSUE THREAD

**Issue by borjalor** [alvarodh5/harvey_unchained#4]
Buenas, desde Return0; os dejamos un código de ejemplo que os puede ser de utilidad para scrappear alguna de las web que teníais en mente. Os dejo aquí la explicación de los dos módulos utilizados: 
PhatomJS (Emulador en background del explorador).
Selenium (WebScrapper)
¡Esperamos que os sirvan!

import unittest
from pprint import pprint
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.by import By
import time

class TestOne(unittest.TestCase):
    def setUp(self):
        # self.display = Display(visible=0, size=(1120, 550))
        # display.start()
        # dcap = dict(DesiredCapabilities.PHANTOMJS)
        # dcap["phantomjs.page.settings.userAgent"] = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.57 Safari/537.36")

        self.driver = webdriver.PhantomJS()
        self.driver.set_window_size(1120, 550)

    def test_url(self):

        self.driver.get("")

        # self.driver.add_cookie(dicts)
        self.driver.find_element_by_name('username').send_keys("")
        self.driver.save_screenshot('out1.png')
        self.driver.find_element_by_name('password').send_keys("")
        self.driver.save_screenshot('out2.png')
        buttons = self.driver.find_elements(By.XPATH, "//button")

        time.sleep(2)
        buttons[0].click()
        time.sleep(3)
        self.driver.save_screenshot('out3.png')
        time.sleep(3)

        #self.driver.find_element(By.LINK_TEXT, "service?s=14786605").click()
        self.driver.find_element_by_xpath('//a[@href="' + "service?s=14786605" + '"]').click()
        #self.driver.find_element_by_css_selector('[href^=service?s=14786605]').click()
        #self.driver.save_screenshot('out4.png')

        time.sleep(5)
        buttons_main = self.driver.find_elements(By.XPATH, "//button")

        main_window_handle = None
        while not main_window_handle:
            main_window_handle = self.driver.current_window_handle

        buttons_main[2].click()
        time.sleep(8)
        self.driver.save_screenshot('out4.png')
        pprint(self.driver.window_handles)

        signin_window_handle = None
        if not signin_window_handle:
            for handle in self.driver.window_handles:
                if handle != main_window_handle:
                    signin_window_handle = handle
                    break
        self.driver.switch_to_alert()

        time.sleep(1)
        self.driver.find_element_by_css_selector('input[type="file"]').send_keys(r"/home/out1.png")
        print(self.driver.current_url)
        time.sleep(2)
        self.driver.save_screenshot('out5.png')
        time.sleep(4)

    def tearDown(self):
        # self.display.stop()
        self.driver.quit()

if name == 'main':
    unittest.main()

**Comment by juanvelascogomez** [comment]
Muchas gracias por vuestra aportación @borjalor, como hemos hablado con varios de vosotros y con el jurado a lo largo de estos días la conclusión ha sido que no teníamos tiempo suficiente para curiosear con la funcionalidad de "PhatomJS" + "Selenium".

No dudaremos en echarle un vistazo en los próximos días para tratar de simplificar al máximo posible el análisis de facebook.

Muchas gracias por la aportación ;)
